name: Test All Platforms
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        jdk: [17.0.1]
        java: ['temurin', 'zulu', 'microsoft', 'liberica']
        os: [ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15]

    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK ${{ matrix.java }} ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.java }}
          java-version: ${{ matrix.jdk }}

      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
          echo "test=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
        
      - name: Rebuild Patches
        run: ./gradlew rebuildPatches --stacktrace

      - name: Create Reobf Jar
        run: ./gradlew createReobfPaperclipJar --stacktrace

      - name: Create Mojmap Jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace
